### PR TITLE
Update for Pandoc 1.15.2; add letterhead option.

### PR DESCRIPTION
**Pull request by adunning**
The letterhead variable takes a PDF file and uses it as the background to the first page only (requires the `wallpaper` package).

### CODE REVIEW

**Comment by aaronwolen** [comment]
The letterhead option is a great idea! Is there a reason you're defaulting its position to the lower right? I think the most common use case would be placing a banner at the top that spans the width of the page.

**Comment by adunning** [comment]
Good point; I had been using a full-page letterhead file, where it didn't matter. Fixed.

**Comment by aaronwolen** [comment]
Perfect, thanks again!

**Comment by adunning** [comment]
You're welcome!

**Pull request merged**
