### PR TITLE
Update for Pandoc 2

### PR DESCRIPTION
**Pull request by adunning**
This reapplies the letter template modifications to the LaTeX template distributed with Pandoc 2.0.0.1, omitting the options for Beamer.

### CODE REVIEW

**Comment by adunning** [comment]
The build is failing because the new template uses the `xcolor` package (for consistency with Beamer), and that's not apparently being loaded, even though [texlive-latex-recommended](https://packages.debian.org/sid/texlive-latex-recommended) is meant to include that. Makes me wonder, rather, whether we should go back to only using `xcolor` with Beamer.

**Comment by aaronwolen** [comment]
Andrew, thanks! This is great.

The xcolor issue with Travis is weird... but I'll leave that for another day.

**Comment by adunning** [comment]
It strikes me now that it might work by removing the `--no-install-recommends` flag, which was likely stopping `texlive-latex-recommended` from being loaded even when it was specified; but I haven't tested this.

**Comment by aaronwolen** [comment]
I skipped `texlive-latex-recommended` because it's a dependency of `texlive-latex-extra`, so it comes along for the ride. That said, I'm going to include it for the sake of being explicit.

It looks like xcolor wasn't bundled with `texlive-latex-recommended` until [Ubuntu Xenial](https://packages.ubuntu.com/xenial/all/texlive-latex-recommended/filelist) and we're running [Trusty](https://packages.ubuntu.com/trusty/all/texlive-latex-recommended/filelist) on Travis.

**Pull request merged**
